{{case_clause,{command,install,
	       'call.route',
	       true,
	       {install,10,undefined},
	       undefined}},
 [{yate,call,2},
  {erl_eval,do_apply,5},
  {shell,exprs,6},
  {shell,eval_loop,3}]}
